language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing to be installed"

before_scripts:
  - echo "no tests"

scripts:
  - docker --version 
  - docker build -t simple-node1 .
  - docker tag simple-node1 luancaius/simple-node1:latest


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push luancaius/simple-node1
